version: '3.9'
services:
  app:
    build: ./app/
    depends_on:
      - db
    ports:
      - '5000:5000'

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: zno
    ports:
      - '5432:5432'

  cache:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
