version: '3.9'
services:
  app:
    build: ./app/
    depends_on:
      - db
    networks:
      - test

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: zno
    ports:
      - '5432:5432'
    networks:
      - test

networks:
  test: